### ISSUE TITLE
Install github actions

### ISSUE THREAD

**Issue by mauriciovieira** [LuCCoelho/TDD-and-Django-studies#3]
After #2, install github actions. I suggest following [a tutorial](https://www.honeybadger.io/blog/django-test-github-actions/#introduction-to-github-actions), but you'll just need something like

```
name: test_Django
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install ruff 
      - run: pip install -r requirements.txt # install all our dependencies for the project
      - run: python manage.py  test 
```

With something like 

```
name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
```
